theme: jekyll-theme-leap-day
title: McKonelab website
description: This is our group website
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Publications
    url: pubs
  - title: Contact
    url: contact
